spring.application.name=craftorderview
server.port=8081
server.error.whitelabel.enabled=false
app.url.base=${APP_BASE_URL:http://localhost:8081}
spring.mvc.format.date-time=dd/MM/yyyy HH:mm
spring.jackson.time-zone=America/Guayaquil
