spring.application.name=craftorderview
server.port=${SERVER_PORT:8081}

server.error.whitelabel.enabled=false
spring.mvc.format.date-time=dd/MM/yyyy HH:mm
spring.jackson.time-zone=America/Guayaquil

app.url.base=${APP_BASE_URL:http://localhost:8080}
